default_context:
  project_name: 'sakholm'
  project_slug: 'sakholm'
  domain_main: 'sakholm.com'
  domain_staging: 'stag.sakholm.com'
  docker_swarm_stack_name_main: 'sakholm-com'
  docker_swarm_stack_name_staging: 'stag-sakholm-com'
  secret_key: '9cb276f90676e430dbb33609046a518c42cf13b4efee2c34d89eca61cbbeec83'
  first_superuser: 'admin@sakholm.com'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.sakholm.com", "https://stag.sakholm.com", "https://sakholm.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@sakholm.com'
  postgres_password: 'password'
  pgadmin_default_user: 'admin@sakholm.com'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'sakholm.com'
  traefik_constraint_tag_staging: 'stag.sakholm.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
